name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'  # 只在推送标签时触发，例如 v1.0.0
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows-exe:
    runs-on: windows-latest  # 使用 Windows 环境
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 指定 Python 版本
        architecture: 'x64'     # 64位架构
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # 安装你的项目依赖
        if exist requirements.txt pip install -r requirements.txt
        
    - name: Build executable with PyInstaller
      run: |
        # 使用 PyInstaller 打包
        pyinstaller --onefile --name "MyApp" --console your_script.py
        # 如果不需要控制台窗口（GUI应用），使用 --windowed 代替 --console
        
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/*.exe
        if-no-files-found: error

    - name: List files in dist directory (for debugging)
      run: |
        dir dist\
